export type Answer = { text: string; points: number };
export type Round = { question: string; answers: Answer[] };
export type CategoryKey = "work" | "family" | "kids" | "food" | "hollywood" | "music";

export const CATEGORIES: { key: CategoryKey; name: string; description: string }[] = [
  { key: "work", name: "Work Feud", description: "Office life, coworkers, and the daily grind" },
  { key: "family", name: "Family Feud", description: "Home, relatives, traditions, and family fun" },
  { key: "kids", name: "Kid Feud", description: "School, playtime, imagination, and kid favorites" },
  { key: "food", name: "Food Feud", description: "Meals, snacks, restaurants, and kitchen classics" },
  { key: "hollywood", name: "Hollywood Feud", description: "Movies, television, celebrities, and showbiz" },
  { key: "music", name: "Music Feud", description: "Songs, concerts, instruments, and music culture" },
];

export const CATEGORY_ROUNDS: Record<CategoryKey, Round[]> = {
  work: [
    { question: "Name something people do first thing on a workday.", answers: [{ text: "Check email", points: 32 }, { text: "Get coffee", points: 27 }, { text: "Check the calendar", points: 18 }, { text: "Say hello to the team", points: 13 }, { text: "Make a to-do list", points: 10 }] },
    { question: "Name something you might find in an office break room.", answers: [{ text: "Coffee maker", points: 35 }, { text: "Refrigerator", points: 25 }, { text: "Microwave", points: 20 }, { text: "Snacks", points: 12 }, { text: "Mugs", points: 8 }] },
    { question: "Name a reason someone might be late to a meeting.", answers: [{ text: "Another meeting ran long", points: 38 }, { text: "Lost track of time", points: 24 }, { text: "Tech trouble", points: 19 }, { text: "Traffic", points: 11 }, { text: "Wrong room", points: 8 }] },
    { question: "Name something that makes a great teammate.", answers: [{ text: "Good communication", points: 31 }, { text: "Reliable", points: 26 }, { text: "Helpful", points: 21 }, { text: "Positive attitude", points: 14 }, { text: "Sense of humor", points: 8 }] },
    { question: "Name something people look forward to on Friday.", answers: [{ text: "The weekend", points: 41 }, { text: "Leaving early", points: 22 }, { text: "Happy hour", points: 17 }, { text: "Casual clothes", points: 12 }, { text: "No alarm tomorrow", points: 8 }] },
    { question: "Name something you might find on an office desk.", answers: [{ text: "Computer", points: 35 }, { text: "Pen", points: 28 }, { text: "Papers", points: 18 }, { text: "Coffee mug", points: 12 }, { text: "Phone", points: 5 }, { text: "Stapler", points: 2 }] },
    { question: "Name a reason people are late to work.", answers: [{ text: "Traffic", points: 42 }, { text: "Overslept", points: 25 }, { text: "Car problems", points: 15 }, { text: "Public transit delay", points: 8 }, { text: "Bad weather", points: 6 }, { text: "Forgot something", points: 4 }] },
    { question: "Name something people complain about at work.", answers: [{ text: "Boss", points: 38 }, { text: "Salary", points: 22 }, { text: "Long hours", points: 18 }, { text: "Coworkers", points: 12 }, { text: "Meetings", points: 6 }, { text: "Workload", points: 4 }] },
    { question: "Name something people do during lunch break.", answers: [{ text: "Eat", points: 45 }, { text: "Check phone", points: 20 }, { text: "Go for a walk", points: 15 }, { text: "Run errands", points: 10 }, { text: "Take a nap", points: 6 }, { text: "Exercise", points: 4 }] },
    { question: "Name something people wear to look professional.", answers: [{ text: "Suit", points: 32 }, { text: "Dress shirt", points: 28 }, { text: "Tie", points: 20 }, { text: "Dress shoes", points: 12 }, { text: "Blazer", points: 5 }, { text: "Watch", points: 3 }] },
  ],
  family: [
    { question: "Name something families do together on a Sunday.", answers: [{ text: "Eat dinner", points: 34 }, { text: "Watch TV", points: 25 }, { text: "Go to church", points: 18 }, { text: "Visit relatives", points: 13 }, { text: "Play games", points: 10 }] },
    { question: "Name something a parent reminds a child to do.", answers: [{ text: "Clean their room", points: 31 }, { text: "Do homework", points: 27 }, { text: "Brush their teeth", points: 20 }, { text: "Say thank you", points: 13 }, { text: "Go to bed", points: 9 }] },
    { question: "Name something families argue about in the car.", answers: [{ text: "Directions", points: 34 }, { text: "Music", points: 25 }, { text: "Where to eat", points: 19 }, { text: "Who sits where", points: 13 }, { text: "Temperature", points: 9 }] },
    { question: "Name something you bring to a family picnic.", answers: [{ text: "Food", points: 37 }, { text: "Blanket", points: 23 }, { text: "Drinks", points: 18 }, { text: "Outdoor games", points: 13 }, { text: "Sunscreen", points: 9 }] },
    { question: "Name a family member who gives the best advice.", answers: [{ text: "Mom", points: 36 }, { text: "Dad", points: 27 }, { text: "Grandmother", points: 17 }, { text: "Older sibling", points: 12 }, { text: "Grandfather", points: 8 }] },
    { question: "Name something found in almost every family photo album.", answers: [{ text: "Birthdays", points: 31 }, { text: "Vacations", points: 25 }, { text: "Holidays", points: 21 }, { text: "Babies", points: 14 }, { text: "Weddings", points: 9 }] },
    { question: "Name something relatives ask about at a family gathering.", answers: [{ text: "Your job", points: 30 }, { text: "Your love life", points: 27 }, { text: "Your children", points: 20 }, { text: "School", points: 14 }, { text: "When you are leaving", points: 9 }] },
    { question: "Name a chore families often share.", answers: [{ text: "Washing dishes", points: 32 }, { text: "Taking out trash", points: 25 }, { text: "Laundry", points: 20 }, { text: "Cleaning floors", points: 14 }, { text: "Yard work", points: 9 }] },
    { question: "Name something that gets passed down through a family.", answers: [{ text: "Jewelry", points: 30 }, { text: "Recipes", points: 26 }, { text: "Stories", points: 20 }, { text: "Furniture", points: 14 }, { text: "Clothing", points: 10 }] },
    { question: "Name something families do on vacation.", answers: [{ text: "Go sightseeing", points: 32 }, { text: "Swim", points: 25 }, { text: "Take pictures", points: 20 }, { text: "Eat out", points: 14 }, { text: "Buy souvenirs", points: 9 }] },
  ],
  kids: [
    { question: "Name something kids trade at school.", answers: [{ text: "Snacks", points: 30 }, { text: "Trading cards", points: 27 }, { text: "Stickers", points: 20 }, { text: "Pencils", points: 13 }, { text: "Toys", points: 10 }] },
    { question: "Name something a kid wants at a birthday party.", answers: [{ text: "Cake", points: 34 }, { text: "Presents", points: 29 }, { text: "Friends", points: 17 }, { text: "Games", points: 12 }, { text: "Balloons", points: 8 }] },
    { question: "Name something kids build with blocks.", answers: [{ text: "Tower", points: 38 }, { text: "House", points: 24 }, { text: "Castle", points: 18 }, { text: "Car", points: 12 }, { text: "Robot", points: 8 }] },
    { question: "Name an excuse a kid gives for not doing homework.", answers: [{ text: "Forgot", points: 33 }, { text: "Lost it", points: 23 }, { text: "Did not understand", points: 20 }, { text: "Too busy", points: 14 }, { text: "Pet ate it", points: 10 }] },
    { question: "Name something kids like to do at recess.", answers: [{ text: "Play tag", points: 30 }, { text: "Use the swings", points: 25 }, { text: "Play ball", points: 21 }, { text: "Climb", points: 14 }, { text: "Talk with friends", points: 10 }] },
    { question: "Name something that might be under a kid's bed.", answers: [{ text: "Toys", points: 34 }, { text: "Clothes", points: 25 }, { text: "Shoes", points: 19 }, { text: "Books", points: 13 }, { text: "Dust", points: 9 }] },
    { question: "Name something kids take to a sleepover.", answers: [{ text: "Pajamas", points: 32 }, { text: "Sleeping bag", points: 26 }, { text: "Toothbrush", points: 19 }, { text: "Pillow", points: 14 }, { text: "Favorite toy", points: 9 }] },
    { question: "Name something kids hope to see at a zoo.", answers: [{ text: "Lion", points: 30 }, { text: "Elephant", points: 26 }, { text: "Monkey", points: 21 }, { text: "Giraffe", points: 14 }, { text: "Tiger", points: 9 }] },
    { question: "Name something kids make out of snow.", answers: [{ text: "Snowman", points: 45 }, { text: "Snowball", points: 23 }, { text: "Snow angel", points: 16 }, { text: "Fort", points: 10 }, { text: "Igloo", points: 6 }] },
    { question: "Name a place where kids have to use an indoor voice.", answers: [{ text: "Library", points: 38 }, { text: "School", points: 25 }, { text: "Church", points: 18 }, { text: "Museum", points: 11 }, { text: "Doctor's office", points: 8 }] },
  ],
  food: [
    { question: "Name a food people eat with their hands.", answers: [{ text: "Pizza", points: 34 }, { text: "Burger", points: 25 }, { text: "Tacos", points: 19 }, { text: "Sandwich", points: 13 }, { text: "French fries", points: 9 }] },
    { question: "Name something people put on a baked potato.", answers: [{ text: "Butter", points: 32 }, { text: "Sour cream", points: 26 }, { text: "Cheese", points: 21 }, { text: "Bacon", points: 13 }, { text: "Chives", points: 8 }] },
    { question: "Name a food that is hard to eat neatly.", answers: [{ text: "Spaghetti", points: 31 }, { text: "Tacos", points: 26 }, { text: "Ribs", points: 20 }, { text: "Ice cream cone", points: 14 }, { text: "Sloppy joe", points: 9 }] },
    { question: "Name something found at a breakfast buffet.", answers: [{ text: "Eggs", points: 30 }, { text: "Bacon", points: 26 }, { text: "Pancakes", points: 20 }, { text: "Fruit", points: 14 }, { text: "Cereal", points: 10 }] },
    { question: "Name a food people dip into another food.", answers: [{ text: "Chips", points: 35 }, { text: "French fries", points: 24 }, { text: "Chicken nuggets", points: 19 }, { text: "Vegetables", points: 13 }, { text: "Cookies", points: 9 }] },
    { question: "Name something you might order extra spicy.", answers: [{ text: "Wings", points: 33 }, { text: "Curry", points: 24 }, { text: "Salsa", points: 19 }, { text: "Tacos", points: 14 }, { text: "Noodles", points: 10 }] },
    { question: "Name a dessert served at a birthday party.", answers: [{ text: "Cake", points: 49 }, { text: "Ice cream", points: 24 }, { text: "Cupcakes", points: 14 }, { text: "Cookies", points: 8 }, { text: "Brownies", points: 5 }] },
    { question: "Name something people add to coffee.", answers: [{ text: "Cream", points: 36 }, { text: "Sugar", points: 30 }, { text: "Milk", points: 17 }, { text: "Flavored syrup", points: 10 }, { text: "Whipped cream", points: 7 }] },
    { question: "Name a food that smells strong when cooking.", answers: [{ text: "Fish", points: 34 }, { text: "Bacon", points: 25 }, { text: "Garlic", points: 20 }, { text: "Popcorn", points: 13 }, { text: "Cabbage", points: 8 }] },
    { question: "Name something commonly served at a barbecue.", answers: [{ text: "Burgers", points: 31 }, { text: "Hot dogs", points: 26 }, { text: "Ribs", points: 20 }, { text: "Corn", points: 14 }, { text: "Potato salad", points: 9 }] },
  ],
  hollywood: [
    { question: "Name something seen on a Hollywood red carpet.", answers: [{ text: "Celebrities", points: 35 }, { text: "Cameras", points: 25 }, { text: "Fancy dresses", points: 19 }, { text: "Reporters", points: 13 }, { text: "Fans", points: 8 }] },
    { question: "Name a job listed in movie credits.", answers: [{ text: "Actor", points: 32 }, { text: "Director", points: 26 }, { text: "Producer", points: 20 }, { text: "Writer", points: 13 }, { text: "Editor", points: 9 }] },
    { question: "Name something movie stars might have in a dressing room.", answers: [{ text: "Mirror", points: 34 }, { text: "Makeup", points: 25 }, { text: "Costumes", points: 19 }, { text: "Snacks", points: 13 }, { text: "Flowers", points: 9 }] },
    { question: "Name a type of movie that often has a sequel.", answers: [{ text: "Superhero", points: 34 }, { text: "Action", points: 25 }, { text: "Horror", points: 20 }, { text: "Animated", points: 13 }, { text: "Science fiction", points: 8 }] },
    { question: "Name something people buy at a movie theater.", answers: [{ text: "Popcorn", points: 44 }, { text: "Soda", points: 25 }, { text: "Candy", points: 18 }, { text: "Tickets", points: 8 }, { text: "Nachos", points: 5 }] },
    { question: "Name something that can ruin a movie ending.", answers: [{ text: "A spoiler", points: 39 }, { text: "Predictable twist", points: 23 }, { text: "Bad acting", points: 17 }, { text: "Sudden cliffhanger", points: 13 }, { text: "Someone talking", points: 8 }] },
    { question: "Name a place where a movie scene might be filmed.", answers: [{ text: "Studio", points: 31 }, { text: "City street", points: 25 }, { text: "House", points: 20 }, { text: "Beach", points: 14 }, { text: "School", points: 10 }] },
    { question: "Name something an actor might do before an audition.", answers: [{ text: "Practice lines", points: 36 }, { text: "Dress for the part", points: 23 }, { text: "Calm their nerves", points: 18 }, { text: "Warm up", points: 14 }, { text: "Research the role", points: 9 }] },
    { question: "Name something associated with an awards show.", answers: [{ text: "Trophies", points: 31 }, { text: "Acceptance speeches", points: 25 }, { text: "Red carpet", points: 21 }, { text: "Designer outfits", points: 14 }, { text: "Live performances", points: 9 }] },
    { question: "Name a reason someone stops watching a television series.", answers: [{ text: "It became boring", points: 32 }, { text: "Favorite character left", points: 24 }, { text: "Too many seasons", points: 19 }, { text: "Canceled subscription", points: 14 }, { text: "Bad ending", points: 11 }] },
  ],
  music: [
    { question: "Name something people do when their favorite song starts.", answers: [{ text: "Sing along", points: 38 }, { text: "Dance", points: 27 }, { text: "Turn it up", points: 18 }, { text: "Smile", points: 10 }, { text: "Record a video", points: 7 }] },
    { question: "Name something a musician brings to a concert.", answers: [{ text: "Instrument", points: 39 }, { text: "Microphone", points: 22 }, { text: "Sheet music", points: 17 }, { text: "Water", points: 13 }, { text: "Backup strings", points: 9 }] },
    { question: "Name a place where people sing even if they are not professionals.", answers: [{ text: "Shower", points: 34 }, { text: "Car", points: 27 }, { text: "Karaoke bar", points: 20 }, { text: "Church", points: 12 }, { text: "Birthday party", points: 7 }] },
    { question: "Name an instrument found in a rock band.", answers: [{ text: "Guitar", points: 38 }, { text: "Drums", points: 27 }, { text: "Bass", points: 19 }, { text: "Keyboard", points: 10 }, { text: "Microphone", points: 6 }] },
    { question: "Name something fans buy at a concert.", answers: [{ text: "T-shirt", points: 37 }, { text: "Poster", points: 22 }, { text: "Drinks", points: 18 }, { text: "Album", points: 13 }, { text: "Hat", points: 10 }] },
    { question: "Name a reason a song gets stuck in your head.", answers: [{ text: "Catchy chorus", points: 39 }, { text: "Heard it repeatedly", points: 25 }, { text: "Simple lyrics", points: 16 }, { text: "Memorable beat", points: 12 }, { text: "Commercial jingle", points: 8 }] },
    { question: "Name something people use to listen to music.", answers: [{ text: "Phone", points: 39 }, { text: "Headphones", points: 24 }, { text: "Car radio", points: 18 }, { text: "Smart speaker", points: 11 }, { text: "Record player", points: 8 }] },
    { question: "Name a song people commonly hear at a wedding.", answers: [{ text: "First dance song", points: 31 }, { text: "Celebration", points: 25 }, { text: "A love ballad", points: 20 }, { text: "Dance party song", points: 15 }, { text: "Father-daughter song", points: 9 }] },
    { question: "Name something a singer does to protect their voice.", answers: [{ text: "Drink water", points: 36 }, { text: "Warm up", points: 25 }, { text: "Rest their voice", points: 19 }, { text: "Drink tea", points: 12 }, { text: "Avoid shouting", points: 8 }] },
    { question: "Name a reason someone skips to the next song.", answers: [{ text: "They dislike it", points: 38 }, { text: "Wrong mood", points: 23 }, { text: "Too slow", points: 17 }, { text: "Heard it too often", points: 13 }, { text: "Long intro", points: 9 }] },
  ],
};
